### ISSUE TITLE
Get error when open 'Home' from Desktop

### ISSUE THREAD

**Issue by claudiunv** [os-js/OS.js#293]
An unexpected error occurred, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occurred, and if you can; how to replicate it

```
TypeError: doTranslate is not a function
    at ApplicationFileManagerWindow.checkSelection (http://192.168.60.4/packages/default/FileManager/main.js:249:19)
    at Object.view._call.done (http://192.168.60.4/packages/default/FileManager/main.js:427:14)
    at http://192.168.60.4/client/javascript/gui/fileview.js:497:18
    at http://192.168.60.4/client/javascript/gui/fileview.js:301:7
    at http://192.168.60.4/client/javascript/gui/fileview.js:251:7
    at http://192.168.60.4/client/javascript/vfs.js:719:7
    at http://192.168.60.4/client/javascript/vfs/_null.js:52:7
    at null.<anonymous> (http://192.168.60.4/client/javascript/vfs.js:265:9)
    at null.<anonymous> (http://192.168.60.4/client/javascript/api.js:325:11)
    at Object.data.onsuccess (http://192.168.60.4/client/javascript/handler.js:336:21)
```

**Comment by andersevenrud** [comment]
This was fixed in 1f23c14023ec4784b6c05867e35c02cab4f70c5b. You probably just need to update your repo.

Let me know if that worked

**Comment by claudiunv** [comment]
It's working, thanks.

**Comment by andersevenrud** [comment]
Great! :)
