### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by myliu1999** [os-js/OS.js#306]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationSettingsWindow.setContainer (http://osjsv2.0o.no/packages/default/Settings/combined.js:213:28)
    at UIElement.<anonymous> (http://osjsv2.0o.no/packages/default/Settings/combined.js:189:14)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1115:18)
    at select (http://osjsv2.0o.no/osjs.js:5756:12)
    at context (http://osjsv2.0o.no/osjs.js:5763:9)
    at HTMLElement.<anonymous> (http://osjsv2.0o.no/osjs.js:5801:9)
    at HTMLElement.cbNormal (http://osjsv2.0o.no/osjs.js:1115:18)
```

**Comment by eraffaelli** [comment]
What were you doing when this occurred?
From what I can read, you were in settings, but did you do something specific?

**Comment by andersevenrud** [comment]
I'm guessing this is something that happened after an async event and something was detached.
