### ISSUE TITLE
An unexpected error occured, maybe a bug. PTY Terminal Application

### ISSUE THREAD

**Issue by rodrigoselau** [os-js/OS.js#357]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ReferenceError: Terminal is not defined
    at PTYTerminal.init (http://192.168.10.60:8000/packages/extras/TerminalExtension/extension.js:168:20)
    at ApplicationTerminalWindow.init (http://192.168.10.60:8000/packages/extras/Terminal/main.js:92:19)
    at Process.WindowManager.addWindow (http://192.168.10.60:8000/client/javascript/windowmanager.js:543:7)
    at Process.Application._addWindow (http://192.168.10.60:8000/client/javascript/application.js:214:12)
    at http://192.168.10.60:8000/packages/extras/Terminal/main.js:189:12
    at Object.Utils.ajax.onsuccess (http://192.168.10.60:8000/client/javascript/gui/_scheme.js:252:9)
    at XMLHttpRequest.onReadyStateChange (http://192.168.10.60:8000/client/javascript/utils/xhr.js:106:16)
```

**Comment by andersevenrud** [comment]
This means that you don't have the dependencies install properly. `Terminal` should be a gobal object

**Comment by rodrigoselau** [comment]
aah, so sorry, thank your help

**Comment by andersevenrud** [comment]
Don't be sorry, man :)
