### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by icocos** [os-js/OS.js#360]
发生未知异常, 也许是个BUG.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'querySelector' of null
    at UIScheme._findDOM (https://osjsv2.0o.no/osjs.js:5547:15)
    at UIScheme.find (https://osjsv2.0o.no/osjs.js:5530:20)
    at resetLastSelected (https://osjsv2.0o.no/osjs.js:8514:19)
    at Object.view._call.done (https://osjsv2.0o.no/osjs.js:8522:13)
    at https://osjsv2.0o.no/osjs.js:7393:18
    at https://osjsv2.0o.no/osjs.js:7249:7
    at https://osjsv2.0o.no/osjs.js:7192:9
    at https://osjsv2.0o.no/osjs.js:9709:7
    at https://osjsv2.0o.no/osjs.js:11477:7
    at https://osjsv2.0o.no/osjs.js:11451:18
```

**Comment by andersevenrud** [comment]
Should be fixed now (but demo server has not been updated). Thanks :)
