### ISSUE TITLE
[Applications] IDE - Deleting application does not remove from metadata

### ISSUE THREAD

**Issue by EnderNator10** [os-js/OS.js#373]
Een onverwachte fout opgetreden, mogelijk een bug.

> Vriendelijk verzoek dit probleem te rapporteren. Voeg een korte omschrijving toe en als het lukt; Hoe we dit kunnen nabootsen

```
TypeError: Cannot read property 'selectQuery' of undefined
    at Process.ApplicationIDE.onElementSelected (http://212.19.220.144:8000/packages/default/IDE/main.js:384:29)
    at UIElement.<anonymous> (http://212.19.220.144:8000/packages/default/IDE/window-properties.js:135:11)
    at HTMLElement.cbNormal (http://212.19.220.144:8000/client/javascript/utils/dom.js:569:20)
    at select (http://212.19.220.144:8000/client/javascript/gui/_dataview.js:368:12)
    at context (http://212.19.220.144:8000/client/javascript/gui/_dataview.js:377:9)
    at HTMLElement.<anonymous> (http://212.19.220.144:8000/client/javascript/gui/_dataview.js:421:9)
    at HTMLElement.cbNormal (http://212.19.220.144:8000/client/javascript/utils/dom.js:569:20)
```

**Comment by andersevenrud** [comment]
You only got this once, or do you know how to replicate it ? Because "some old stuff" does not mean much to me :)

To me it seems like the editor tried to select a element that does not exist. Do you know which one you selected ?

**Comment by EnderNator10** [comment]
well i deleted a application i made then i tryed clicking it and it regenerated evereytime i refreshed and whne it regened the error whas gone but everytime i delete it this happened i did manage to deleted it but that whas when i deleted all inclusing the source folder

**Comment by andersevenrud** [comment]
I'm still not quite sure what you mean by this.

You deleted the application physically ?  Then clicked what ?

**Comment by EnderNator10** [comment]
i deleted a application a clicked it afterwards

**Comment by EnderNator10** [comment]
but it regenerated after a server reboot

**Comment by andersevenrud** [comment]
Ok. So, you:

1. Made an application with IDE
2. Deleted said application
3. Restarted and tried to start it
4. Got error message ?

Deleting an application will make an error, because it was not "uninstalled"

**Comment by EnderNator10** [comment]
yes thas basicley what happened

**Comment by andersevenrud** [comment]
**NOTE TO SELF**: Add VFS listener on the `home://.packages` path to regenerate the index

**Comment by andersevenrud** [comment]
This should be solved now

**Comment by EnderNator10** [comment]
thank you :)
