### ISSUE TITLE
three.js doesn't launch

### ISSUE THREAD

**Issue by hjek** [os-js/OS.js#381]
An error occured while trying to launch: ApplicationThreejs

> Application 'ApplicationThreejs' init() failed: TypeError: Cannot read property 'getExtension' of null

```
TypeError: Cannot read property 'getExtension' of null
    at get (https://cdnjs.cloudflare.com/ajax/libs/three.js/r74/three.min.js:683:263)
    at new THREE.WebGLRenderer (https://cdnjs.cloudflare.com/ajax/libs/three.js/r74/three.min.js:643:135)
    at MyScene.init (https://osjsv2.0o.no/packages/experiments/Threejs/combined.js:61:21)
    at ApplicationThreejsWindow._inited (https://osjsv2.0o.no/packages/experiments/Threejs/combined.js:320:18)
    at Process.WindowManager.addWindow (https://osjsv2.0o.no/osjs.js:4419:7)
    at Process.Application._addWindow (https://osjsv2.0o.no/osjs.js:2789:12)
    at Process.ApplicationThreejs.init (https://osjsv2.0o.no/packages/experiments/Threejs/combined.js:350:10)
    at _callback (https://osjsv2.0o.no/osjs.js:1970:11)
    at https://osjsv2.0o.no/osjs.js:2016:13
```

**Comment by andersevenrud** [comment]
I'm pretty sure this error is because your browser does not support 3D accelerated rendering, which this application uses.

I'll make it so the error is a bit nicer

**Comment by andersevenrud** [comment]
This seems to be a vendor and/or OS problem: https://github.com/mrdoob/three.js/issues/4927

I have at least added a proper error dialog/message when this occurs: https://github.com/os-js/OS.js-experimental/commit/9e30fdf8942c86e53a1ca63a301f08e48b59274d
