### ISSUE TITLE
search bug

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#393]
Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
TypeError: OSjs.Core.getSearchEngine is not a function
    at PanelItemSearch.search (http://localhost:8000/packages/default/CoreWM/panelitems/search.js:223:15)
    at HTMLInputElement.<anonymous> (http://localhost:8000/packages/default/CoreWM/panelitems/search.js:121:14)
    at HTMLInputElement.cbNormal (http://localhost:8000/client/javascript/utils/dom.js:569:20)
```

**Comment by andersevenrud** [comment]
Search Engine is not complete in anyway, so expect bugs. Also it has its own issue already which you made #385
