### ISSUE TITLE
problem in closing the IDE

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#395]
Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
TypeError: Cannot read property 'find' of null
    at ApplicationIDEWindow.update (http://localhost:8000/packages/OS.js-development/IDE/window-main.js:117:32)
    at UIElement.menuEvent (http://localhost:8000/packages/OS.js-development/IDE/window-main.js:101:12)
    at HTMLLabelElement.cbNormal (http://localhost:8000/client/javascript/utils/dom.js:569:20)
    at HTMLElement.<anonymous> (http://localhost:8000/client/javascript/gui/menus.js:63:18)
    at HTMLElement.cbNormal (http://localhost:8000/client/javascript/utils/dom.js:569:20)
```

**Comment by andersevenrud** [comment]
Should be fixed in https://github.com/os-js/OS.js-development/commit/d62041939ecb47e5af0fbc4d0f279bce89b29aa4
