### ISSUE TITLE
error opening the parameters.

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#397]
Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
TypeError: Cannot read property 'Icon' of undefined
    at http://localhost:8000/packages/default/Settings/main.js:463:42
    at Array.forEach (native)
    at renderItems (http://localhost:8000/packages/default/Settings/main.js:458:23)
    at ApplicationSettingsWindow.initPanelTab (http://localhost:8000/packages/default/Settings/main.js:541:5)
    at ApplicationSettingsWindow.updateSettings (http://localhost:8000/packages/default/Settings/main.js:203:10)
    at ApplicationSettingsWindow.init (http://localhost:8000/packages/default/Settings/main.js:154:10)
    at Process.WindowManager.addWindow (http://localhost:8000/client/javascript/windowmanager.js:536:7)
    at Process.Application._addWindow (http://localhost:8000/client/javascript/application.js:232:12)
    at http://localhost:8000/packages/default/Settings/main.js:658:12
    at Object.Utils.ajax.onsuccess (http://localhost:8000/client/javascript/gui/_scheme.js:252:9)
```

**Comment by andersevenrud** [comment]
This is most likely because you were using the `search-engine` branch and switched over to `master` or something.

It is complaining about the missing Search section.

**Comment by andersevenrud** [comment]
https://github.com/os-js/OS.js/commit/ac0c163272c8023b468887340fb53e61daabf274 Should prevent this error from happening
