### ISSUE TITLE
says 'children' of null at 1051

### ISSUE THREAD

**Issue by antcolag** [os-js/OS.js#429]
Si è verificato un errore inaspettato, forse un bug.

> Per piacere, fai un report se pensi che questo sia un bug.  Includi una breve descrizione di come l'errore si è verificato, se possibile come replicarlo.

```
TypeError: Cannot read property 'children' of null
    at Object.OSjs.Utils.$index (https://osjsv2.0o.no/osjs.js:1051:55)
    at HTMLElement.select (https://osjsv2.0o.no/osjs.js:6499:25)
    at whenFinished (https://osjsv2.0o.no/osjs.js:1148:24)
    at HTMLElement.cbe (https://osjsv2.0o.no/osjs.js:1179:11)
```

**Comment by andersevenrud** [comment]
This has already been fixed, the demo server is just outdated.
