### ISSUE TITLE
clicking on /awstats

### ISSUE THREAD

**Issue by antcolag** [os-js/OS.js#431]
Si è verificato un errore inaspettato, forse un bug.

> Per piacere, fai un report se pensi che questo sia un bug.  Includi una breve descrizione di come l'errore si è verificato, se possibile come replicarlo.

```
Error: Cannot doLaunchFile() without a mime type
    at Object.doLaunchFile [as open] (https://osjsv2.0o.no/osjs.js:1764:32)
    at https://osjsv2.0o.no/packages/default/FileManager/combined.js:369:11
    at Array.forEach (native)
    at ApplicationFileManagerWindow.checkActivation (https://osjsv2.0o.no/packages/default/FileManager/combined.js:363:19)
    at UIElement.<anonymous> (https://osjsv2.0o.no/packages/default/FileManager/combined.js:269:14)
    at HTMLElement.cbNormal (https://osjsv2.0o.no/osjs.js:1204:20)
    at UIElement.<anonymous> (https://osjsv2.0o.no/osjs.js:7815:10)
    at HTMLElement.cbNormal (https://osjsv2.0o.no/osjs.js:1204:20)
    at HTMLElement.activate (https://osjsv2.0o.no/osjs.js:6505:12)
    at HTMLElement.cbNormal (https://osjsv2.0o.no/osjs.js:1204:20)
```

**Comment by andersevenrud** [comment]
This is just because /awstats is a virtual directory (and restricted) on my webserver. So not a bug, actually :)

I should make this entry invisible.

**Comment by andersevenrud** [comment]
This should no longer be a problem as I have re-configured the server. Thanks for reporting :)
