### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by Adagal** [os-js/OS.js#450]
**This bugreport was generated by OS.js:**

> Error inesperado, puede que sea un bug.

> Por favor, informa de esto si piensas que es un bug.
Incluye una breve descripción sobre cómo se produjo el probleñam y si es posible, cómo reproducirlo. Gracias

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36","platform":"Win32","language":"es","appVersion":"5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"}
```

## Stack Trace 
```
TypeError: Cannot read property 'value' of undefined
    at keyEvents.(anonymous function) (https://osjsv2.0o.no/packages/default/CoreWM/combined.js:2604:16)
    at https://osjsv2.0o.no/packages/default/CoreWM/combined.js:2635:31
    at HTMLInputElement.mouseEventHandler (https://osjsv2.0o.no/osjs.js:1096:18)
```

**Comment by andersevenrud** [comment]
Should be fixed now. Thanks for reporting!
