### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by WorkQing** [os-js/OS.js#481]
**This bugreport was generated by OS.js:**

> 发生未知异常, 也许是个BUG.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36","platform":"Win32","language":"zh-CN","appVersion":"5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36"}
```

## Stack Trace 
```
TypeError: Cannot read property 'find' of null
    at ApplicationGmailWindow.renderMessages (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1719:28)
    at https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2366:15
    at GoogleMail._checkConnection (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:507:7)
    at GoogleMail.getMessages (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:770:16)
    at https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2314:19
    at GoogleMail._checkConnection (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:507:7)
    at GoogleMail.getFolders (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:526:16)
    at Process.ApplicationGmail.sync (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2305:17)
    at https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:2102:14
    at https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:385:9
```

**Comment by andersevenrud** [comment]
There's quite a few bugs in this application and already have an issue; #216.

Thanks for reporting!
