### ISSUE TITLE
Arduino TIAN Chaos Calmer Openwrt

### ISSUE THREAD

**Issue by AdamSyahputra** [os-js/OS.js#482]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoPackageManagerWindow.renderView (http://10.10.9.242/packages/target/ArduinoPackageManager/combined.js?54919:143:35)
    at http://10.10.9.242/packages/target/ArduinoPackageManager/combined.js?54919:120:12
    at http://10.10.9.242/packages/target/ArduinoPackageManager/combined.js?54919:289:7
    at _Handler.<anonymous> (http://10.10.9.242/packages/target/ArduinoPackageManager/combined.js?54919:249:14)
    at _Handler.<anonymous> (http://10.10.9.242/osjs.js:1689:11)
    at Object.onsuccess (http://10.10.9.242/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://10.10.9.242/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
This has been fixed and is pending an official update. I'll notify you when it is done :)
