### ISSUE TITLE
[Automated Bugreport] {category: 'user'} in argument settings shortcut

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#496]
**This bugreport was generated by OS.js:**

> Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.
 Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36","platform":"Linux x86_64","language":"fr","appVersion":"5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36"}
```

## Stack Trace 
```
SyntaxError: Unexpected token c in JSON at position 1
    at Object.parse (native)
    at IconViewShortcutDialog.applySettings (https://localhost:8000/packages/default/CoreWM/iconview.js:95:29)
    at UIElement.<anonymous> (https://localhost:8000/packages/default/CoreWM/iconview.js:81:12)
    at HTMLButtonElement.mouseEventHandler (https://localhost:8000/client/javascript/utils/events.js:476:27)
```

**Comment by andersevenrud** [comment]
You have to input valid JSON. Example:

```
{"category":"user"}
```

Notice the double quotes. Do you have it like this ?

**Comment by andersevenrud** [comment]
I'm pretty sure my comment above was the problem, so I'm closing this. Feel free to reopen if you have any more issues :)

**Comment by vlotho** [comment]
no, it does not.
