### ISSUE TITLE
Could not run the server

### ISSUE THREAD

**Issue by HuJK** [os-js/OS.js#505]
## Expected behaviour
Run the server sucessfully

## Actual behaviour
pi@raspberrypi:~/OS.js$ ./bin/start-dist.sh

`UNCAUGHT EXCEPTION { [Error: ENOENT, no such file or directory /home/pi/OS.js/src/server/packages.json']
  errno: 34,
  code: 'ENOENT',
  path: '/home/pi/OS.js/src/server/packages.json',
  syscall: 'open' } Error: ENOENT, no such file or directory '/home/pi/OS.js/src/server/packages.json'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at Object.module.exports.init (/home/pi/OS.js/src/server/node/core/index.js:170:35)
    at Object.module.exports.listen (/home/pi/OS.js/src/server/node/http.js:460:22)
    at /home/pi/OS.js/src/server/node/server.js:82:11
    at Object.<anonymous> (/home/pi/OS.js/src/server/node/server.js:90:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
UNCAUGHT EXCEPTION [TypeError: Cannot read property 'handler' of undefined] TypeError: Cannot ead property 'handler' of undefined
    at Object.module.exports.close (/home/pi/OS.js/src/server/node/http.js:530:13)
    at process._server.listen.port (/home/pi/OS.js/src/server/node/server.js:75:13)
    at process.emit (events.js:95:17)`

## (Optinal) Browser and OS information
Raspberry pi

**Comment by HuJK** [comment]
Sorry,I gorfot install nodejs-legacy before install OS.js.
