### ISSUE TITLE
node

### ISSUE THREAD

**Issue by saibai** [os-js/OS.js#512]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at https://yun.local/packages/target/ArduinoPackageManager/combined.js?12788:288:28
    at https://yun.local/packages/target/ArduinoPackageManager/combined.js?12788:260:14
    at _Handler.<anonymous> (https://yun.local/osjs.js:1756:7)
    at Object.onerror (https://yun.local/osjs.js:9466:17)
    at XMLHttpRequest.onReadyStateChange (https://yun.local/osjs.js:1266:16)
```

**Comment by andersevenrud** [comment]
Hi,

This issue has already been resolved and is pending an official update.

Thanks for reporting :)
