### ISSUE TITLE
error on update package

### ISSUE THREAD

**Issue by unfinished** [os-js/OS.js#517]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://stpyun.local/packages/target/ArduinoPackageManager/combined.js?1962:282:28
    at _Handler.<anonymous> (http://stpyun.local/packages/target/ArduinoPackageManager/combined.js?1962:254:16)
    at _Handler.<anonymous> (http://stpyun.local/osjs.js:1692:14)
    at Object.onerror (http://stpyun.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://stpyun.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
This issue has already been fixed, but is pending an official update from Arduino.
