### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by webmst** [os-js/OS.js#528]
**This bugreport was generated by OS.js 2.0-alpha80:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36","platform":"Win32","language":"it","appVersion":"5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"}
```

## Stack Trace 
```
TypeError: onInited is not a function
    at http://osjs.noip.me/packages/extras/Chat/combined.js:6437:7
    at http://osjs.noip.me/osjs.js:6839:11
    at http://osjs.noip.me/osjs.js:6782:7
    at next (http://osjs.noip.me/osjs.js:1372:16)
    at Object.OSjs.Utils.asyncs (http://osjs.noip.me/osjs.js:1382:7)
    at resolveExternalFragments (http://osjs.noip.me/osjs.js:6758:11)
    at Object.onsuccess (http://osjs.noip.me/osjs.js:6836:9)
    at XMLHttpRequest.onReadyStateChange (http://osjs.noip.me/osjs.js:1679:16)
```

**Comment by andersevenrud** [comment]
Hi! Thanks for reporting.

I think your `extras` repository is outdated, because this is not an issue anymore.

Try to update the codebase :)
