### ISSUE TITLE
Error while update of a package. 

### ISSUE THREAD

**Issue by sunarang** [os-js/OS.js#531]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.0.26/packages/target/ArduinoPackageManager/combined.js?46151:282:28
    at ArduinoHandler.<anonymous> (http://192.168.0.26/packages/target/ArduinoPackageManager/combined.js?46151:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.0.26/osjs.js:1692:14)
    at Object.onerror (http://192.168.0.26/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.0.26/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting.

This has been fixed and is pending an official update :)

Ref: #517
