### ISSUE TITLE
Error update ArduinoOS

### ISSUE THREAD

**Issue by Cubel89** [os-js/OS.js#536]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.1.104/packages/target/ArduinoPackageManager/combined.js?24469:282:28
    at _Handler.<anonymous> (http://192.168.1.104/packages/target/ArduinoPackageManager/combined.js?24469:254:16)
    at _Handler.<anonymous> (http://192.168.1.104/osjs.js:1692:14)
    at Object.onerror (http://192.168.1.104/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.104/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi!

Thanks for reporting. This bug has already been fixed and is pending an official update.

If you want I can notify you once it is out
