### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MullerGuy** [os-js/OS.js#538]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://yuncultureollon.local/packages/target/ArduinoPackageManager/combined.js?18561:282:28
    at ArduinoHandler.<anonymous> (http://yuncultureollon.local/packages/target/ArduinoPackageManager/combined.js?18561:254:16)
    at ArduinoHandler.<anonymous> (http://yuncultureollon.local/osjs.js:1692:14)
    at Object.onerror (http://yuncultureollon.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://yuncultureollon.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

Sorry for late reply, but been busy this holiday.

This issue has already been fixed and is pending an official update from Arduino. If you want I can notify you when this is ready
