### ISSUE TITLE
Build Error - unable to build

### ISSUE THREAD

**Issue by mistergibson** [os-js/OS.js#553]
## Expected behaviour
(normal build output)

## Actual behaviour
node osjs build
module.js:472
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mistergibson/Documents/Development/Aptana/OS.js/src/build/index.js:34:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

## Steps to reproduce the error
node osjs build

## (Optinal) Browser and OS information
Node.js version 7.4.0

**Comment by andersevenrud** [comment]
Run `npm install --production`.

If you upgraded your installation: https://os.js.org/manual/installation/upgrade/

**Comment by mistergibson** [comment]
ok - thanks.  I do that in the future after updates.   Cheers.
