### ISSUE TITLE
Package manager error

### ISSUE THREAD

**Issue by jorgipor** [os-js/OS.js#557]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: (stdout || "").split is not a function
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?45907:295:30
    at ArduinoHandler.<anonymous> (http://arduino.local/packages/target/ArduinoPackageManager/combined.js?45907:260:14)
    at ArduinoHandler.<anonymous> (http://arduino.local/osjs.js:1689:11)
    at Object.onsuccess (http://arduino.local/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
You might have an outdated installation on your board. For more information about these issues, see: #436
