### ISSUE TITLE
why???

### ISSUE THREAD

**Issue by kri118** [os-js/OS.js#558]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.11.6/packages/target/ArduinoPackageManager/combined.js?54810:282:28
    at ArduinoHandler.<anonymous> (http://192.168.11.6/packages/target/ArduinoPackageManager/combined.js?54810:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.11.6/osjs.js:1692:14)
    at Object.onerror (http://192.168.11.6/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.11.6/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
You might have an outdated installation on your board. For more information about these issues, see: #436
