### ISSUE TITLE
Error on Upgrade to arduinoos 2.02 

### ISSUE THREAD

**Issue by m510** [os-js/OS.js#559]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.1.135/packages/target/ArduinoPackageManager/combined.js?30065:282:28
    at ArduinoHandler.<anonymous> (http://192.168.1.135/packages/target/ArduinoPackageManager/combined.js?30065:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.1.135/osjs.js:1692:14)
    at Object.onerror (http://192.168.1.135/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.135/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

There seems to be an issue with some boards and the underlying webserver. There's an issue open on this here: #436
