### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by bukow1cm** [os-js/OS.js#560]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot convert undefined or null to object
    at http://arduino.local/packages/target/ArduinoService/combined.js?18989:98:16
    at http://arduino.local/packages/target/ArduinoService/combined.js?18989:191:7
    at http://arduino.local/packages/target/ArduinoService/combined.js?18989:264:7
    at .<anonymous> (http://arduino.local/osjs.js:1756:7)
    at Object.data.onerror (http://arduino.local/osjs.js:9466:17)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1266:16)
```

**Comment by andersevenrud** [comment]
Hi,

There seems to be an issue with some boards and the underlying webserver. There's an issue open on this here: #436
