### ISSUE TITLE
arduino YUN , NO WIFFI

### ISSUE THREAD

**Issue by antonlor3** [os-js/OS.js#564]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at http://192.168.240.1/packages/target/ArduinoService/combined.js?31924:98:16
    at http://192.168.240.1/packages/target/ArduinoService/combined.js?31924:193:7
    at ArduinoHandler.<anonymous> (http://192.168.240.1/packages/target/ArduinoService/combined.js?31924:269:7)
    at ArduinoHandler.<anonymous> (http://192.168.240.1/osjs.js:1692:14)
    at Object.onerror (http://192.168.240.1/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.240.1/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

There seems to be an issue with some boards and the underlying webserver. There's an issue open on this here: #436 (you can configure your board using Luci instead -- see comments)
