### ISSUE TITLE
Error Updating arduinoos package

### ISSUE THREAD

**Issue by drwaky** [os-js/OS.js#566]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://boby.local/packages/target/ArduinoPackageManager/combined.js?20485:282:28
    at ArduinoHandler.<anonymous> (http://boby.local/packages/target/ArduinoPackageManager/combined.js?20485:254:16)
    at ArduinoHandler.<anonymous> (http://boby.local/osjs.js:1692:14)
    at Object.onerror (http://boby.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://boby.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

There's an open issue on this here: #436
