### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ericboy0224** [os-js/OS.js#567]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'ssid' of undefined
    at http://192.168.43.163/packages/target/ArduinoWizardSettings/combined.js?20637:225:34
    at ArduinoHandler.API.call.err (http://192.168.43.163/packages/target/ArduinoWizardSettings/combined.js?20637:524:24)
    at ArduinoHandler.<anonymous> (http://192.168.43.163/osjs.js:1689:11)
    at Object.onsuccess (http://192.168.43.163/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://192.168.43.163/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
Hi,

There's an open issue on this here: #436
