### ISSUE TITLE
CIAO Config

### ISSUE THREAD

**Issue by jpnila** [os-js/OS.js#568]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoCiaoConfiguratorWindow.showConnectorConf (http://172.16.102.222/packages/target/ArduinoCiaoConfigurator/combined.js?63352:217:41)
    at ApplicationCodeMirror.cm_core.destroy (http://172.16.102.222/packages/target/ArduinoCiaoConfigurator/combined.js?63352:202:18)
    at ApplicationCodeMirror.Application._onMessage (http://172.16.102.222/osjs.js:2781:14)
    at ApplicationCodeMirror.DefaultApplication._onMessage (http://172.16.102.222/osjs.js:11665:38)
    at ApplicationCodeMirrorWindow.Window.destroy (http://172.16.102.222/osjs.js:3365:17)
    at ApplicationCodeMirrorWindow.destroy (http://172.16.102.222/packages/target/CodeMirror/combined.js?16007:12370:30)
    at ApplicationCodeMirrorWindow.Window._close (http://172.16.102.222/osjs.js:3465:10)
    at ApplicationCodeMirrorWindow.DefaultApplicationWindow._close (http://172.16.102.222/osjs.js:11864:29)
    at ApplicationCodeMirrorWindow.Window._onWindowButtonClick (http://172.16.102.222/osjs.js:3901:12)
    at HTMLElement.<anonymous> (http://172.16.102.222/osjs.js:3168:14)
```

**Comment by andersevenrud** [comment]
This issue has been resolved (in a separate repository) and the patch will be applied on the next update.
