### ISSUE TITLE
Have Something Wrong

### ISSUE THREAD

**Issue by LeoCindy** [os-js/OS.js#579]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://yun.local/packages/target/ArduinoPackageManager/combined.js?68764:282:28
    at ArduinoHandler.<anonymous> (http://yun.local/packages/target/ArduinoPackageManager/combined.js?68764:254:16)
    at ArduinoHandler.<anonymous> (http://yun.local/osjs.js:1692:14)
    at Object.onerror (http://yun.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://yun.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

Please see #436 for more information about issues on Arduino.
