### ISSUE TITLE
Yun Update

### ISSUE THREAD

**Issue by rasaPi** [os-js/OS.js#587]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?19249:282:28
    at ArduinoHandler.<anonymous> (http://arduino.local/packages/target/ArduinoPackageManager/combined.js?19249:254:16)
    at ArduinoHandler.<anonymous> (http://arduino.local/osjs.js:1692:14)
    at Object.onerror (http://arduino.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

Please see #436 for information on how to work around issues for your device.
