### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bimberman** [os-js/OS.js#588]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://aquaponics.local/packages/target/ArduinoPackageManager/combined.js?55500:282:28
    at ArduinoHandler.<anonymous> (http://aquaponics.local/packages/target/ArduinoPackageManager/combined.js?55500:254:16)
    at ArduinoHandler.<anonymous> (http://aquaponics.local/osjs.js:1692:14)
    at Object.onerror (http://aquaponics.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://aquaponics.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
