### ISSUE TITLE
JavaScript Bug Report

### ISSUE THREAD

**Issue by nazuna1** [os-js/OS.js#589]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: 정의되지 않음 또는 null 참조인 'ssid' 속성을 가져올 수 없습니다.
   at Anonymous function (http://172.30.1.48/packages/target/ArduinoWizardSettings/combined.js?22070:225:17)
   at Anonymous function (http://172.30.1.48/packages/target/ArduinoWizardSettings/combined.js?22070:524:17)
   at Anonymous function (http://172.30.1.48/osjs.js:1689:7)
   at data.onsuccess (http://172.30.1.48/osjs.js:8867:9)
   at onReadyStateChange (http://172.30.1.48/osjs.js:1199:11)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
