### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WellCho89** [os-js/OS.js#590]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoPackageManagerWindow.renderView (http://192.168.50.33/packages/target/ArduinoPackageManager/combined.js?73007:143:35)
    at http://192.168.50.33/packages/target/ArduinoPackageManager/combined.js?73007:120:12
    at http://192.168.50.33/packages/target/ArduinoPackageManager/combined.js?73007:289:7
    at ArduinoHandler.<anonymous> (http://192.168.50.33/packages/target/ArduinoPackageManager/combined.js?73007:249:14)
    at ArduinoHandler.<anonymous> (http://192.168.50.33/osjs.js:1689:11)
    at Object.onsuccess (http://192.168.50.33/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://192.168.50.33/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
