### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by WellCho89** [os-js/OS.js#591]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at http://192.168.50.8/packages/target/ArduinoService/combined.js?29100:98:16
    at http://192.168.50.8/packages/target/ArduinoService/combined.js?29100:193:7
    at ArduinoHandler.<anonymous> (http://192.168.50.8/packages/target/ArduinoService/combined.js?29100:269:7)
    at ArduinoHandler.<anonymous> (http://192.168.50.8/osjs.js:1692:14)
    at Object.onerror (http://192.168.50.8/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.50.8/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
