### ISSUE TITLE
ApplicationMap, failed on start

### ISSUE THREAD

**Issue by rddownloads** [os-js/OS.js#593]
TypeError: onInited is not a function
    at http://127.0.0.1:8000/FS/read?path=home%3A%2F%2F%2F.packages%2FTest%2Fmain.js:86:7
    at http://127.0.0.1:8000/osjs.min.js:34:860
    at http://127.0.0.1:8000/osjs.min.js:33:31443
    at r (http://127.0.0.1:8000/osjs.min.js:33:7940)
    at Object.OSjs.Utils.asyncs (http://127.0.0.1:8000/osjs.min.js:33:8003)
    at u (http://127.0.0.1:8000/osjs.min.js:33:31104)
    at Object.onsuccess (http://127.0.0.1:8000/osjs.min.js:34:821)
    at XMLHttpRequest.t (http://127.0.0.1:8000/osjs.min.js:33:13072)

**Comment by andersevenrud** [comment]
Ah, the "Map" package is *very* outdated. I did not make it, but I'll look into it.

It's in a separate repository.
