### ISSUE TITLE
OS upgrade

### ISSUE THREAD

**Issue by jamieharwood** [os-js/OS.js#594]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.1.123/packages/target/ArduinoPackageManager/combined.js?78295:282:28
    at ArduinoHandler.<anonymous> (http://192.168.1.123/packages/target/ArduinoPackageManager/combined.js?78295:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.1.123/osjs.js:1692:14)
    at Object.onerror (http://192.168.1.123/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.123/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
