### ISSUE TITLE
windows installer , uncaught exception occured TypeError: The header content contains invalid characters , graceful-fs module

### ISSUE THREAD

**Issue by scenaristeur** [os-js/OS.js#601]
Hi! very good job that i discovered for my Arduino Yun.
 Then, I tried the windows installer on windows 10, node version : 6.5, npm: 4.0.5, and got this error , running on powershell.

PS C:\osjs> node osjs run
Loading: Logger with level 7
Using: Proxy http-bind-jabber/
Loading: Generic C:/osjs/src/server/node/modules/generic/example.js
Loading: Middleware C:/osjs/src/server/node/modules/middleware/example.js
Loading: Middleware C:/osjs/src/server/node/modules/middleware/user-package.js
Loading: Session \src\server\node\modules\session\memory.js
Loading: API C:/osjs/src/server/node/modules/api/application.js
Loading: API C:/osjs/src/server/node/modules/api/auth.js
Loading: API C:/osjs/src/server/node/modules/api/curl.js
Loading: API C:/osjs/src/server/node/modules/api/packages.js
Loading: API C:/osjs/src/server/node/modules/api/storage.js
Loading: API C:/osjs/src/server/node/modules/api/users.js
Loading: Authenticator \src\server\node\modules\auth\demo.js
Loading: Storage \src\server\node\modules\storage\demo.js
Loading: VFS Transport C:/osjs/src/server/node/modules/vfs/example.js
Loading: VFS Transport C:/osjs/src/server/node/modules/vfs/filesystem.js
Loading: VFS Transport C:/osjs/src/server/node/modules/vfs/http.js
Loading: Configuration \src\server\packages.json
Loading: Application \src\packages\default\CoreWM\server\main.js
Loading: Application \src\packages\default\Settings\server\main.js
Loading: Service C:/osjs/src/server/node/modules/services/broadway.js
Loading: Service C:/osjs/src/server/node/modules/services/example.js
Loading: Service C:/osjs/src/server/node/modules/services/vfswatch.js
2017-05-28T23:58:32.836Z Starting OS.js server
2017-05-28T23:58:32.837Z Running http on localhost:8000
2017-05-28T23:58:32.838Z Running in production mode
2017-05-28T23:58:32.839Z Ready...
An uncaught exception occured TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.setWriteHeadHeaders (C:\osjs\node_modules\on-headers\index.js:82:19)
    at ServerResponse.writeHead (C:\osjs\node_modules\on-headers\index.js:41:36)
    at ReadStream.stream.on (C:\osjs\src\server\node\core\responder.js:171:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at C:\osjs\node_modules\graceful-fs\graceful-fs.js:193:14
    at C:\osjs\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.setWriteHeadHeaders (C:\osjs\node_modules\on-headers\index.js:82:19)
    at ServerResponse.writeHead (C:\osjs\node_modules\on-headers\index.js:41:36)
    at ReadStream.stream.on (C:\osjs\src\server\node\core\responder.js:171:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at C:\osjs\node_modules\graceful-fs\graceful-fs.js:193:14
    at C:\osjs\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)
2017-05-29T00:01:10.671Z Trying to shut down sanely...
PS C:\osjs>

Any idea ?

thx

**Comment by andersevenrud** [comment]
Hi,

I've never seen this one before. What language do you use on your OS ?

I've updated some dependencies, so if you want to try to upgrade, then please do -- and try again.

https://www.os-js.org/manual/installation/upgrade/

**Comment by andersevenrud** [comment]
Also, could you try to run with `node osjs run --debug --loglevel=15`.

**Comment by andersevenrud** [comment]
I'm closing this due to lack of response.

However, there's been some changes that might have resolved this issue. I don't know. But if you do find time to test and it's still not working, please re-open this issue.
