### ISSUE TITLE
actualizando

### ISSUE THREAD

**Issue by jacasal** [os-js/OS.js#603]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoPackageManagerWindow.renderView (http://10.0.0.20/packages/target/ArduinoPackageManager/combined.js?37519:143:35)
    at http://10.0.0.20/packages/target/ArduinoPackageManager/combined.js?37519:120:12
    at http://10.0.0.20/packages/target/ArduinoPackageManager/combined.js?37519:289:7
    at ArduinoHandler.<anonymous> (http://10.0.0.20/packages/target/ArduinoPackageManager/combined.js?37519:249:14)
    at ArduinoHandler.<anonymous> (http://10.0.0.20/osjs.js:1689:11)
    at Object.onsuccess (http://10.0.0.20/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://10.0.0.20/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436
