### ISSUE TITLE
Tried to open "Arduino Process Viewer" in osjs on Arduino TIAN

### ISSUE THREAD

**Issue by ltheoret** [os-js/OS.js#612]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Unable to get property 'PID' of undefined or null reference
   at Anonymous function (http://192.168.0.20/packages/target/ArduinoProcessViewer/combined.js?19423:82:13)
   at Array.prototype.forEach (native code)
   at Anonymous function (http://192.168.0.20/packages/target/ArduinoProcessViewer/combined.js?19423:81:12)
   at Anonymous function (http://192.168.0.20/packages/target/ArduinoProcessViewer/combined.js?19423:64:9)
   at Anonymous function (http://192.168.0.20/osjs.js:1754:7)
   at data.onsuccess (http://192.168.0.20/osjs.js:9463:9)
   at onReadyStateChange (http://192.168.0.20/osjs.js:1263:11)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436 (#436 (comment) )
