### ISSUE TITLE
just setting it up...

### ISSUE THREAD

**Issue by beaudamore** [os-js/OS.js#626]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://beauyun.local/packages/target/ArduinoPackageManager/combined.js?23727:282:28
    at ArduinoHandler.<anonymous> (http://beauyun.local/packages/target/ArduinoPackageManager/combined.js?23727:254:16)
    at ArduinoHandler.<anonymous> (http://beauyun.local/osjs.js:1692:14)
    at Object.onerror (http://beauyun.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://beauyun.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Marking as duplicate of #627
