### ISSUE TITLE
update packages arduino yun

### ISSUE THREAD

**Issue by tecnologiacreativa** [os-js/OS.js#631]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.0.172/packages/target/ArduinoPackageManager/combined.js?33848:282:28
    at ArduinoHandler.<anonymous> (http://192.168.0.172/packages/target/ArduinoPackageManager/combined.js?33848:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.0.172/osjs.js:1692:14)
    at Object.onerror (http://192.168.0.172/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.0.172/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: `http://<your-board-ip>/cgi-bin/luci`

Ref: https://github.com/os-js/OS.js/issues/436
