### ISSUE TITLE
upgrading a brand new (today) Yun. booted it, told me it needed an update, then this

### ISSUE THREAD

**Issue by beaudamore** [os-js/OS.js#632]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?13453:282:28
    at ArduinoHandler.<anonymous> (http://arduino.local/packages/target/ArduinoPackageManager/combined.js?13453:254:16)
    at ArduinoHandler.<anonymous> (http://arduino.local/osjs.js:1692:14)
    at Object.onerror (http://arduino.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: `http://<your-board-ip>/cgi-bin/luci`

Ref: https://github.com/os-js/OS.js/issues/436
