### ISSUE TITLE
arduino yun wifi configure error ( AJAX error) 

### ISSUE THREAD

**Issue by ksk12** [os-js/OS.js#634]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: (stdout || "").split is not a function
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?41784:295:30
    at ArduinoHandler.<anonymous> (http://arduino.local/packages/target/ArduinoPackageManager/combined.js?41784:260:14)
    at ArduinoHandler.<anonymous> (http://arduino.local/osjs.js:1689:11)
    at Object.onsuccess (http://arduino.local/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://<your-board-ip>/cgi-bin/luci

Ref: #436
