### ISSUE TITLE
Arduibo yun

### ISSUE THREAD

**Issue by vincenzosuraci** [os-js/OS.js#636]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.1.205/packages/target/ArduinoPackageManager/combined.js?69996:282:28
    at ArduinoHandler.<anonymous> (http://192.168.1.205/packages/target/ArduinoPackageManager/combined.js?69996:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.1.205/osjs.js:1692:14)
    at Object.onerror (http://192.168.1.205/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.205/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://arduino-ip/cgi-bin/luci

Ref: #436
