### ISSUE TITLE
Can't run app on RasPi?

### ISSUE THREAD

**Issue by alimohamad** [os-js/OS.js#643]
## Expected behaviour
I'm trying to run the demo on Raspberry Pi. I've already installed Node and NPM through terminal. Just want to try the app.

## Actual behaviour
When I run the command node osjs build, I get this error message:

```javascript
module.js:327
    throw err;
    ^

Error: Cannot find module 'osjs-build'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/Documents/OS.js/osjs:6:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

## Steps to reproduce the error

1. Download the app
2. Run npm install
3. Run node osjs build

**Comment by andersevenrud** [comment]
Npm istall probably failed because you are on ARM. You'll need to install a
PhantomJS binary first.

I'm away from my computer, but when I get back I can direct you to some
documentation.

21. okt. 2017 18:55 skrev "Ali Mohamad" <notifications@github.com>:

**Comment by andersevenrud** [comment]
Install this binary then try to install OS.js.

https://github.com/fg2it/phantomjs-on-raspberry

**Comment by alimohamad** [comment]
Hey, thanks so much for your help! when I ran npm install -g, I got this error:

```javascript

npm ERR! error rolling back Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/OS.js'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  OS.js@2.1.5 { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/OS.js']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js' }
npm ERR! Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/OS.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/OS.js']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: '/usr/local/lib/node_modules/OS.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /home/pi/Documents/OS.js
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/OS.js
npm ERR! syscall rmdir
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! stack Error: EACCES: permission denied, rmdir '/usr/local/lib/node_modules/OS.js'
npm ERR! stack     at Error (native)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Documents/OS.js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jbourdale** [comment]
Run the command as root as the npm error say.
Run 
```
su root 
```
to log as root. Or use sudo [ npm install ] but i'm not sure sudo is availible on rasPi

**Comment by alimohamad** [comment]
New error message:

```javascript
npm WARN engine semantic-release@8.2.0: wanted: {"node":">=4","npm":">=2"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! tar.unpack untar error /root/.npm/bluebird/3.5.1/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/express-session/node_modules/depd'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  OS.js@2.1.5 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/express-session/node_modules/depd']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/express-session/node_modules/depd' }
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'semantic-release/commit-analyzer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'semantic-release'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.41-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /home/pi/Documents/OS.js
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! tar.unpack untar error /root/.npm/qs/6.5.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/mime-db/1.30.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/delayed-stream/1.0.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/iconv-lite/0.4.19/package.tgz
npm ERR! tar.unpack untar error /root/.npm/loader-utils/1.1.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/remove-trailing-separator/1.1.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/safe-buffer/5.1.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/har-schema/2.0.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/request/node_modules/har-validator/node_modules/ajv'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  request@2.83.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/request/node_modules/har-validator/node_modules/ajv']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/request/node_modules/har-validator/node_modules/ajv' }
npm ERR! tar.unpack untar error /root/.npm/asynckit/0.4.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/debug/2.6.9/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/body-parser/node_modules/type-is/node_modules/mime-types'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  body-parser@1.18.2 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/body-parser/node_modules/type-is/node_modules/mime-types']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/body-parser/node_modules/type-is/node_modules/mime-types' }
npm ERR! tar.unpack untar error /root/.npm/ajv/5.2.3/package.tgz
npm ERR! tar.unpack untar error /root/.npm/balanced-match/1.0.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  glob@7.1.2 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules' }
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/osjs-scheme-loader/node_modules/webpack'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  osjs-scheme-loader@1.0.9 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/osjs-scheme-loader/node_modules/webpack']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/osjs-scheme-loader/node_modules/webpack' }
npm ERR! tar.unpack untar error /root/.npm/is-extglob/1.0.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/parse-glob/3.0.4/package.tgz
npm ERR! tar.unpack untar error /root/.npm/object.omit/2.0.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/arr-diff/2.0.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/filename-regex/2.0.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/braces/1.8.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/regex-cache/0.4.4/package.tgz
npm ERR! tar.unpack untar error /root/.npm/array-unique/0.2.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/kind-of/3.2.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/extglob/0.3.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/expand-brackets/0.1.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/mime-db/1.30.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  brace-expansion@1.1.8 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map' }
npm ERR! tar.unpack untar error /root/.npm/graceful-fs/4.1.11/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/chokidar/node_modules/readdirp/node_modules/minimatch'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  chokidar@1.7.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/OS.js/node_modules/chokidar/node_modules/readdirp/node_modules/minimatch']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/OS.js/node_modules/chokidar/node_modules/readdirp/node_modules/minimatch' }
npm ERR! tar.unpack untar error /root/.npm/readable-stream/2.3.3/package.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Documents/OS.js/npm-debug.log
npm ERR! not ok code 0
```

The error message says "'semantic-release/commit-analyzer' is not in the npm registry." where can I find/install that? And is there anything else I should do?

**Comment by andersevenrud** [comment]
First off, you should not do any of this as `root` (that means using sudo or su). If you don't have a regular user on your Pi, make one. Then make sure to *always* use that user for installing OS.js. Anything else will just lead to problems.


Now, I noticed that it's installing in `/usr/local/lib/node_modules/OS.js` which is kind of weird. What did you do to initially install OS.js ?

Normally, you'd just:

* Log in as a regular user (ending up in ex `/home/alimohamad`)
* Install PhanotomJS with the link I provided (this however, requires sudo)
* Clone OS.js using git
* Enter OS.js directory
* `npm install`
* `node osjs build`
* `node osjs run`

Assuming, of course, you have a supported Node version installed.

**Comment by andersevenrud** [comment]
I also just saw this:

```
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
```

You do not have a supported node version installed. Use `nvm` to get the latest version of both node and npm installed into your user account on the Pi (as noted in last comment, make a proper user!)

https://github.com/creationix/nvm

**Comment by andersevenrud** [comment]
Since I now know that this is an issue with your environment on the Pi and not a problem with OS.js; I will close this issue. I'll still help you get it running though, so keep posting here :)

**Comment by andersevenrud** [comment]
So, just to summarize:

1. Create a proper user and use it to log in
2. Install latest node
    * `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash`
    * Then *log out and back in*
    * `nvm install node`
    * `nvm use node`
3. Install PhantomJS binary
4. Install OS.js
    * `git clone git@github.com:os-js/OS.js.git`
    * `cd OS.js`
    * `npm install`
    * `node osjs build`
    * `node osjs run`

**Comment by alimohamad** [comment]
Awesome! will do all this right away. Thank you so much!

Also, quick question - I know that OS.js has a second repo with add-ons. I could have sworn a month or two ago there was a terminal add-on, but it's gone now. What happened to it?

**Comment by andersevenrud** [comment]
The "old" terminal app was replaced with Xterm. You can find it on the Org account: https://github.com/os-js/osjs-xterm
