### ISSUE TITLE
error updating packages

### ISSUE THREAD

**Issue by molinadavid** [os-js/OS.js#644]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://arduinokun.local/packages/target/ArduinoPackageManager/combined.js?54332:282:29
    at ArduinoHandler.<anonymous> (http://arduinokun.local/packages/target/ArduinoPackageManager/combined.js?54332:254:16)
    at ArduinoHandler.<anonymous> (http://arduinokun.local/osjs.js:1692:14)
    at Object.onerror (http://arduinokun.local/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://arduinokun.local/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://arduino-ip/cgi-bin/luci

Ref: #436
