### ISSUE TITLE
sdg

### ISSUE THREAD

**Issue by anze123** [os-js/OS.js#655]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: cbError is not a function
    at Object.onerror (http://192.168.1.10/osjs.js:8907:9)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.10/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
This issue has been reported, ref: #436
