### ISSUE TITLE
I don't know what happen to my Arduino Yun

### ISSUE THREAD

**Issue by epicenteryoun** [os-js/OS.js#656]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoPackageManagerWindow.renderView (http://dochwi.local/packages/target/ArduinoPackageManager/combined.js?37995:143:36)
    at http://dochwi.local/packages/target/ArduinoPackageManager/combined.js?37995:120:12
    at http://dochwi.local/packages/target/ArduinoPackageManager/combined.js?37995:289:7
    at ArduinoHandler.<anonymous> (http://dochwi.local/packages/target/ArduinoPackageManager/combined.js?37995:249:14)
    at ArduinoHandler.<anonymous> (http://dochwi.local/osjs.js:1689:11)
    at Object.onsuccess (http://dochwi.local/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://dochwi.local/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://arduino-ip/cgi-bin/luci

Ref: #436
