### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by gaurishrane** [os-js/OS.js#657]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'find' of null
    at ApplicationArduinoPackageManagerWindow.renderView (http://fameiot.local/packages/target/ArduinoPackageManager/combined.js?46581:143:36)
    at http://fameiot.local/packages/target/ArduinoPackageManager/combined.js?46581:120:12
    at http://fameiot.local/packages/target/ArduinoPackageManager/combined.js?46581:289:7
    at ArduinoHandler.<anonymous> (http://fameiot.local/packages/target/ArduinoPackageManager/combined.js?46581:249:14)
    at ArduinoHandler.<anonymous> (http://fameiot.local/osjs.js:1689:11)
    at Object.onsuccess (http://fameiot.local/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://fameiot.local/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://arduino-ip/cgi-bin/luci

Ref: #436
