### ISSUE TITLE
[v3] Error while installing themes and applications

### ISSUE THREAD

**Issue by filips123** [os-js/OS.js#688]
## Expected behaviour

Themes and applications should be installed without any errors.

## Actual behaviour

There is an error. After that, installed theme or application works normally.

## Steps to reproduce the error

1. `git clone -b v3 --single-branch https://github.com/os-js/OS.js.git && cd OS.js`
2. `npm install`
3. `npm run package:install -- https://github.com/os-js/osjs-standard-theme.git`
4. `npm run package:install -- https://github.com/os-js/osjs-example-application.git`

## Output and logs

**Output:**

```bash
user@020507ea28df /projects/OS.js $ npm run package:install -- https://github.com/os-js/osjs-example-application.git

> @osjs/osjs@3.0.0-alpha.27 package:install /projects/OS.js
> osjs-cli package:install "https://github.com/os-js/osjs-example-application.git"

▶  package:install Initialized timer...
package:install …  awaiting  Downloading into /tmp/osjs_1531566679500
Cloning into '/tmp/osjs_1531566679500'...
remote: Counting objects: 62, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 62 (delta 1), reused 3 (delta 1), pack-reused 56
Unpacking objects: 100% (62/62), done.
Checking connectivity... done.
package:install …  awaiting  Installing into /projects/OS.js/src/packages/MyApplication
package:install …  awaiting  Installing npm dependencies....
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.683s
found 0 vulnerabilities

package:install ✔  success   Package installed.
TypeError: logger.remind is not a function
    at Object.module.exports [as package:install] (/projects/OS.js/node_modules/@osjs/cli/src/tasks/install.js:120:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @osjs/osjs@3.0.0-alpha.27 package:install: `osjs-cli package:install "https://github.com/os-js/osjs-example-application.git"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @osjs/osjs@3.0.0-alpha.27 package:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-14T11_11_21_013Z-debug.log
```

**Log file:**

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package:install',
1 verbose cli   '--',
1 verbose cli   'https://github.com/os-js/osjs-example-application.git' ]
2 info using npm@6.2.0
3 info using node@v8.11.1
4 verbose run-script [ 'prepackage:install',
4 verbose run-script   'package:install',
4 verbose run-script   'postpackage:install' ]
5 info lifecycle @osjs/osjs@3.0.0-alpha.27~prepackage:install: @osjs/osjs@3.0.0-alpha.27
6 info lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: @osjs/osjs@3.0.0-alpha.27
7 verbose lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: unsafe-perm in lifecycle true
8 verbose lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/projects/OS.js/node_modules/.bin:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: CWD: /projects/OS.js
10 silly lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: Args: [ '-c',
10 silly lifecycle   'osjs-cli package:install "https://github.com/os-js/osjs-example-application.git"' ]
11 silly lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: Returned: code: 1  signal: null
12 info lifecycle @osjs/osjs@3.0.0-alpha.27~package:install: Failed to exec package:install script
13 verbose stack Error: @osjs/osjs@3.0.0-alpha.27 package:install: `osjs-cli package:install "https://github.com/os-js/osjs-example-application.git"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @osjs/osjs@3.0.0-alpha.27
15 verbose cwd /projects/OS.js
16 verbose Linux 3.10.0-862.3.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "package:install" "--" "https://github.com/os-js/osjs-example-application.git"
18 verbose node v8.11.1
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error @osjs/osjs@3.0.0-alpha.27 package:install: `osjs-cli package:install "https://github.com/os-js/osjs-example-application.git"`
22 error Exit status 1
23 error Failed at the @osjs/osjs@3.0.0-alpha.27 package:install script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by andersevenrud** [comment]
This was fixed in a realease 30 minutes ago. Please run `npm update`.
