### ISSUE TITLE
osjs-build/cli.js Error

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [os-js/OS.js#690]
## Expected behaviour

Builds.

## Actual behaviour

`node osjs build` throws an error:

```

/home/username/scripts/OS.js/node_modules/osjs-build/cli.js:50
  let args = [];
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/username/scripts/OS.js/node_modules/osjs-build/index.js:33:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

I am on Ubuntu 16.04 and have installed nodejs-legacy.

**Comment by SpaceboyRoss01** [comment]
If nodejs-legacy is installed, then version 6.0.0 of Node.js is installed. Uninstall nodejs-legacy and install nvm (Node Version Manager) from the github repository and run nvm install 8.0.0

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 Since he's using v2, node 6 should work fine. Seems like he might have an even older version (I think the support he gets an error for landed in 5).

So using nvm is probably a good idea.

**Comment by Engineer-of-Stuff** [comment]
I uninstalled node-legacy and installed node v8 with npm.

`node osjs install` now gives an error.

module.js:487
    throw err;
    ^

Error: Cannot find module 'osjs-build'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/username/scripts/OS.js/osjs:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by andersevenrud** [comment]
Remove `node_modules/`, `package-lock.json` and re-run `npm install`. Upgrading node versions might lead to some strange errors.

**Comment by Engineer-of-Stuff** [comment]
Thanks for the quick reply!

It worked and I was able to run it. Thanks for the help everyone.

**Comment by andersevenrud** [comment]
Awesome :)

**Comment by andersevenrud** [comment]
Just FYI, I'm working on v3

https://manual.os-js.org/v3/
