### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by ReinforceZwei** [os-js/OS.js#698]
I am running Debian on Raspberry Pi 3 and node version is v10.12.0
I am trying to build osjs.
But I got two error and it stop.
The error message are:

ERROR in /home/pi/OS.js/node_modules/then-jsonp/browser.js
Module not found: Error: Can't resolve 'then-request/lib/handle-qs.js' in '/home/pi/OS.js/node_modules/then-jsonp'
 @ /home/pi/OS.js/node_modules/then-jsonp/browser.js 4:15-55
 @ ./javascript/helpers/google-api.js
 @ ./javascript ^\.\/.*$
 @ ./javascript/boot.js
 @ multi ./javascript/boot.js ./stylesheets/core.css ./stylesheets/gui.css

Error: Command failed: /home/pi/OS.js/node_modules/.bin/webpack --progress --hide-modules
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:648:13)
    at Promise (/home/pi/OS.js/node_modules/ygor/index.js:70:13)
    at new Promise (<anonymous>)
    at Function.shell (/home/pi/OS.js/node_modules/ygor/index.js:68:10)
    at Object.execWebpack (/home/pi/OS.js/node_modules/osjs-build/utils.js:169:15)
    at Object.build:core (/home/pi/OS.js/node_modules/osjs-build/cli.js:197:19)
    at Object.build:core (/home/pi/OS.js/node_modules/osjs-build/cli.js:343:24)
    at run (/home/pi/OS.js/node_modules/ygor/index.js:106:29)
    at tryCatcher (/home/pi/OS.js/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/pi/OS.js/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/pi/OS.js/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/pi/OS.js/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/OS.js/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/OS.js/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/OS.js/node_modules/bluebird/js/release/promise.js:614:10)

**Comment by IngwiePhoenix** [comment]
Can you verify that the supposedly missing file is actually present or not? Alternatively, I’d just install the missing module on your own. As in, navigate into /home/pi/OS.js and run

  $ npm install then-jsonp

then retry to build.

**Comment by andersevenrud** [comment]
Seems like there's something going on with the dependencies. I think Ingwie's answer should fix it.

If not, I suggest you try v3 as this is the version that's being updated and supported at the moment:

https://manual.os-js.org/v3/install

**Comment by andersevenrud** [comment]
Since there's been no activity in this issue since October, I'm closing this.

If you have any objections or progress on the matter, just notify me here and I'll re-open :blush:
