### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by xgakpinar** [os-js/OS.js#753]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'ssid' of undefined
    at http://arduino.local/packages/target/ArduinoSettings/combined.js?41618:210:27
    at ArduinoHandler.API.call.timeout (http://arduino.local/packages/target/ArduinoSettings/combined.js?41618:79:16)
    at ArduinoHandler.<anonymous> (http://arduino.local/osjs.js:1689:11)
    at Object.onsuccess (http://arduino.local/osjs.js:8867:19)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
Please see #436 (comment) for ways to work around this issue.
